
name: Release to Gradle plugin portal

on:
  workflow_dispatch:
    inputs:
      version:
        description: typescript-generator version
        required: true
        type: string

jobs:
  release:
    runs-on: windows-latest
    steps:

      - name: Checkout workflow
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Execute Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          build-root-directory: build\typescript-generator-gradle-plugin-publisher
          arguments: printVersion publishPlugins
        env:
          ORG_GRADLE_PROJECT_version: ${{ inputs.version }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
